In [1]:
import numpy as np

In [3]:
matriksA = np.array([[1,2],[3,4]])
print(matriksA)

[[1 2]
 [3 4]]


In [4]:
matriksB = np.array([[5,6],[7,8]])
print(matriksB)

[[5 6]
 [7 8]]


In [5]:
matriksC = matriksA + matriksB
print(matriksC)

[[ 6  8]
 [10 12]]


In [6]:
matriksD = matriksA - matriksB
print(matriksD)

[[-4 -4]
 [-4 -4]]


In [7]:
matriksE = np.dot(matriksA,matriksB)
print(matriksE)

[[19 22]
 [43 50]]


In [8]:
matriksF = np.linalg.det([[1,2],[3,4]])
print(matriksF)

-2.0000000000000004


In [10]:
matriksG = np.array([[1,1],[2,1],[3,3]])
print(matriksG.transpose())

[[1 2 3]
 [1 1 3]]
